version: "3"

services:
  app:
    build: .
    ports:
      - "8005:8001"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge